version: "3"

services:
  backend:
    build: ./php
  frontend:
    build: ./public_html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/pwp/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/fullchain.pem:/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/fullchain.pem
      - /docker-volumes/pwp/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/privkey.pem:/etc/letsencrypt/live/dont-blindly-copy-past.face-palm/privkey.pem
